services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: co2-backend
    ports:
      - "8072:8072"
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    volumes:
      - ./data:/app/data:rw
    restart: unless-stopped
    environment:
      - TZ=Asia/Yekaterinburg
